# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b648863833cba7cddb20f3c33068cfff1770d590a07a0b434a692e63e0c79ca319daa6d1e18678801dfebd167a5b3d71ea05ddffccedbaa626ff747f3f53921

test:
  secret_key_base: 3aa6b869823918f1bfbd1f76b088f3fffbe2038d703b403e4e35ea75b68547f554c22cb5df4032905f2044596d494e20594f672d22c770f73af148cd6eaad398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
